### ISSUE TITLE
Start sfx_quake?

### ISSUE THREAD

**Issue by Xymph** [Erick194/DOOM64-RE#10]
Since [T_Quake stops](https://github.com/Erick194/DOOM64-RE/blob/main/doom64/p_misc.c#L498) sfx_quake, shouldn't [P_SpawnQuake](https://github.com/Erick194/DOOM64-RE/blob/main/doom64/p_misc.c#L513) start it instead of also stop it? Is that a decompilation oversight or a bug in the original code?

**Comment by Erick194** [comment]
Perform a quick review and this is how the code is written.
Thanks for reviewing.
