### ISSUE TITLE
p_pspr.c function name comments

### ISSUE THREAD

**Issue by Xymph** [Erick194/DOOM64-RE#11]
[This line](https://github.com/Erick194/DOOM64-RE/blob/main/doom64/p_pspr.c#L103) should say P_RecursiveSound

[This line](https://github.com/Erick194/DOOM64-RE/blob/main/doom64/p_pspr.c#L729): A_ChainSawReady

[This line](https://github.com/Erick194/DOOM64-RE/blob/main/doom64/p_pspr.c#L779): A_PlasmaAnimate

**Comment by Erick194** [comment]
A few slight oversights, but I will correct them, thanks for reviewing.
