### ISSUE TITLE
Accuracy compared to original ROM?

### ISSUE THREAD

**Issue by thekovic** [Erick194/DOOM64-RE#8]
Hello, I was wondering if this project has ever produced a ROM with an identical checksum to the original ROM (like the SM64 decompilation project, for example). I know this definitely isn't the case in the current state of master since there were enhancements committed (like, for example, enabling Nightmare difficulty) but I'm wondering if it ever has been.

**Comment by Erick194** [comment]
Hello, the added improvements do not make the checksum different, it is the code itself, I could delete everything and leave it as the original and the checksum will be different, that is the N64 SDK compiler, in the case of SM64 I understand that a large part of the decompilation was in ASM MIPS where all the values are the same as the original ROM, memory addresses too, and I did not decompile the native functions of the Doom64 ROM, I used those of the most recent official N64 SDK.
So this project did not get the original checksum at any time.

Fun fact, the word Nightmare is in the original Doom64 ROM, but they dropped that difficulty in the final version.

Greetings.
